# Generated by Django 5.2.6 on 2025-09-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='paid_order_count',
        ),
    ]
