# Generated by Django 5.2.6 on 2025-10-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_paid_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_points_redeemed',
            field=models.IntegerField(default=0),
        ),
    ]
