# Generated by Django 5.2.5 on 2025-09-02 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.menucategory')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_qty', models.IntegerField()),
                ('reason', models.CharField(choices=[('ADJUST', 'Adjust'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund'), ('CORRECTION', 'Correction'), ('WASTAGE', 'Wastage')], default='ADJUST', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.menuitem')),
            ],
            options={
                'indexes': [models.Index(fields=['menu_item', 'created_at'], name='catalog_ite_menu_it_b228b0_idx'), models.Index(fields=['reason'], name='catalog_ite_reason_8b8742_idx')],
            },
        ),
    ]
