# Generated by Django 5.2.6 on 2025-09-23 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstockmovement',
            name='ref_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.menucategory'),
        ),
        migrations.AddField(
            model_name='itemstockmovement',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.menuitem'),
        ),
        migrations.AddIndex(
            model_name='itemstockmovement',
            index=models.Index(fields=['menu_item', 'created_at'], name='catalog_ite_menu_it_b228b0_idx'),
        ),
        migrations.AddIndex(
            model_name='itemstockmovement',
            index=models.Index(fields=['reason'], name='catalog_ite_reason_8b8742_idx'),
        ),
    ]
