# Generated by Django 5.2.6 on 2025-10-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusevent',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
