# Generated by Django 5.2.6 on 2025-10-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderstatusevent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
