# Generated by Django 5.2.6 on 2025-09-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('grid_size', models.PositiveSmallIntegerField(default=3)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('moves', models.PositiveIntegerField(default=0)),
                ('time_ms', models.PositiveIntegerField(default=0)),
                ('points_awarded', models.IntegerField(default=0)),
                ('reward_code', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
    ]
