# Generated by Django 5.2.6 on 2025-09-23 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField(auto_now_add=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('orders_in_last_30m', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['as_of'], name='crowd_crowd_as_of_768a60_idx')],
            },
        ),
    ]
