# Generated by Django 5.2.6 on 2025-10-10 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmenuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chatmenuitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='chatorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='chatorder',
            name='total_price',
        ),
        migrations.AddField(
            model_name='chatmenuitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chatcustomer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='chatmenuitem',
            name='category',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='chatmenuitem',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='chatmenuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='chatorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatcustomer'),
        ),
        migrations.AlterField(
            model_name='chatorder',
            name='status',
            field=models.CharField(default='PLACED', max_length=32),
        ),
    ]
