# Generated by Django 5.2.6 on 2025-09-23 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('PAYHERE', 'PayHere'), ('STRIPE', 'Stripe'), ('MOCK', 'Mock')], default='PAYHERE', max_length=16)),
                ('payment_ref', models.CharField(max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'payment_ref'], name='payments_pa_provide_6f2597_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['order', 'created_at'], name='payments_pa_order_i_4d9364_idx')],
            },
        ),
    ]
