# Generated by Django 5.2.6 on 2025-09-16 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_menu_item_alter_orderitem_item_name_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_created_b8a300_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'created_at'], name='payments_pa_order_i_4d9364_idx'),
        ),
    ]
