import { useEffect, useState } from "react";
import { api } from "../../lib/api.js"; // adjust if needed
import AdminTabs from "../../components/admin/AdminTabs.jsx";

const hours = Array.from({ length: 15 }, (_, i) => 7 + i); // 7 → 21
const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const NEXT = { Quiet: "Normal", Normal: "Busy", Busy: "Quiet" };

export default function AdminCrowd() {
  const [grid, setGrid] = useState({});
  const [loading, setLoading] = useState(true);

  // Fetch predictions on load
  useEffect(() => {
    api.getPredictions()
      .then((data) => {
        const schedule = {};
        data.forEach((item) => {
          const key = `${days.indexOf(item.day)}-${item.hour}`;
          schedule[key] = {
            state: item.state,
            confidence: item.confidence,
          };
        });
        setGrid(schedule);
        setLoading(false);
      })
      .catch((err) => {
        console.error("Failed to load predictions", err);
        setLoading(false);
      });
  }, []);

  // Toggle state + send feedback
  function toggle(d, h) {
    const key = `${d}-${h}`;
    if (!grid[key]) return;

    const current = grid[key].state;
    const nextState = NEXT[current] || "Quiet";

    setGrid((prev) => ({
      ...prev,
      [key]: { ...prev[key], state: nextState },
    }));

    api.sendFeedback({
      day: days[d],
      hour: h,
      state: nextState,
    }).catch((err) => console.error("Feedback failed:", err));
  }

  if (loading) return <p>Loading predictions...</p>;

  return (
    <section className="admin">
      <AdminTabs />
      <h1>Crowd Meter Management (AI-assisted)</h1>
      <p className="muted">
        Predictions are generated by the ML model. Click a cell to override and send feedback.
      </p>

      <div className="crowd-grid">
        <table>
          <thead>
            <tr>
              <th></th>
              {days.map((day, d) => (
                <th key={d}>{day}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {hours.map((h) => (
              <tr key={h}>
                <td>{h}:00</td>
                {days.map((_, d) => {
                  const key = `${d}-${h}`;
                  const cell = grid[key] || { state: "Quiet", confidence: 0 };
                  return (
                    <td
                      key={key}
                      className={`crowd-cell ${cell.state.toLowerCase()}`}
                      title={`Confidence: ${(cell.confidence * 100).toFixed(0)}%`}
                      onClick={() => toggle(d, h)}
                    >
                      {cell.state}
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}
